name: vyberko

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vyberko
      POSTGRES_PASSWORD: vyberko123
      POSTGRES_DB: vyberko
    volumes:
      - vyberko_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  vyberko_data:
